// This file has been automatically generated by the Unreal Header Implementation tool

#include "IcarusModule.h"

void FIcarusModule::StartupModule(){ }
void FIcarusModule::ShutdownModule(){ }
IMPLEMENT_PRIMARY_GAME_MODULE(FDefaultGameModuleImpl, Icarus, "Icarus");
